/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plter_helloc_HelloC */

#ifndef _Included_com_plter_helloc_HelloC
#define _Included_com_plter_helloc_HelloC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_plter_helloc_HelloC
 * Method:    max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_plter_helloc_HelloC_max
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
